### ISSUE TITLE
>100 subscriptions will hang program

### ISSUE THREAD

**Issue by anitarua** [momentohq/client-sdk-dart#55]
topic client on the surface appears to allow >100 subscriptions, but actually trying to get messages from the 101st subscription causes the program to hang (shows no published messages or errors)

quick googling results seemed like dart grpc might not have config for setting the maximum number of concurrent streams, or it might be named something else and will require more research

**Comment by cprice404** [comment]
@anitarua we will need to have a config option to open multiple grpc channels in order to handle this case. probably similar to what we did in the golang client.

**Comment by anitarua** [comment]
not sure if we really need the multiple grpc channels config yet. I think I'll just try to make the sdk return a TopicSubscribeError if the channels are maxed out or otherwise receives an error while getting the first element

**Comment by cprice404** [comment]
agreed, we don't need to add the multiple channels support yet. and actually I think it's okay to keep this as an open issue for now; I'm not aware of anyone with immediate plans to do that many subscriptions from a single device.
